server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Django app file logs
  - job_name: django-apps
    static_configs:
      - targets:
          - localhost
        labels:
          job: django-apps
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            request_id: request_id
            connection_id: connection_id
            session_uuid: session_uuid
            error: error
            method: method
            path: path
            status_code: status_code
            container: container
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000Z" 
      - labels:
          level:
          logger:
          request_id:
          connection_id:
          method:
          container:

  # All container logs via Docker logging driver  
  - job_name: container-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=docker"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - cri: {}
      - labels:
          container:
          service:

 