server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: logstream
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            stream: stream
            log: log
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
      - match:
          selector: '{job="docker-containers"}'
          stages:
            - json:
                expressions:
                  message: log
            - regex:
                expression: '.*"logger":"chat\.consumers".*'
                source: message
            - labels:
                logger:
            - regex:
                expression: '.*"level":"error".*'
                source: message
            - labels:
                level:
            - regex:
                expression: '.*"request_id":"([^"]+)".*'
                source: message
            - labels:
                request_id:

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/lib/docker/containers/*/logs
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            stream: stream
            log: log
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
      - match:
          selector: '{job="nginx"}'
          stages:
            - json:
                expressions:
                  message: log
            - regex:
                expression: '.*nginx.*'
                source: message 